apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: backend
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /auth
            backend:
              service:
                name: user-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /api/users
            backend:
              service:
                name: user-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /api/lodge
            backend:
              service:
                name: lodging-service
                port:
                  number: 8081
          - pathType: Prefix
            path: /api/reservation
            backend:
              service:
                name: reservation-service
                port:
                  number: 8082
          - pathType: Prefix
            path: /api/notifications
            backend:
              service:
                name: notification-service
                port:
                  number: 8084
