apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: backend
  labels: 
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      initContainers:
        - name: init-database
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: user-configmap
            - configMapRef:
                name: postgres-configmap  # must use deployed postgres configuration
            - secretRef:
                name: postgres-secret   # mu
          command: 
            - "sh"
            - "-c"
            - |
              echo "Creating devops_user_db database..."
              psql -h postgres -U postgres -c "CREATE DATABASE devops_user_db;"
              echo "Database devops_user_db created."

      containers:
        - name: user-service
          image: mihajlodj/devops-user-service:1.2.0  # Update with your actual image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: user-configmap
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: db-port
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.backend.svc.cluster.local:5432/devops_user_db 
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: backend
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080

