---
apiVersion: v1
kind: Service
metadata:
  name: postgres-reservation
  namespace: backend
spec:
  selector:
    app: postgres-reservation
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-reservation
  namespace: backend
spec:
  serviceName: postgres-reservation
  selector:
    matchLabels:
      app: postgres-reservation
  template:
    metadata:
      labels:
        app: postgres-reservation
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-reservation
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-reservation
                  key: POSTGRES_PASSWORD
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-reservation
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-reservation-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-reservation-storage
          persistentVolumeClaim:
            claimName: postgres-reservation-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-reservation-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-reservation-pv
  namespace: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-reservation

