apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-configmap
  namespace: backend
data:
  default.conf: |
    server {
      listen 80;
      location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          try_files $uri $uri/ /index.html =404;
        }
      gzip  on;
    }
  # Add all other necessary files similarly
