apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: fe-service
  name: fe-service
  namespace: backend
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: fe-service