global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
    - "prometheus_recording_rules.yml"

scrape_configs:
  - job_name: 'prometheus'

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'hotels-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hotels-service:8081']

  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['reservation-service:8082']

  - job_name: 'rating-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rating-service:8083']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8084']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: [ 'cadvisor:8090' ]


# https://grafana.com/grafana/dashboards/1860-node-exporter-full/
# https://grafana.com/grafana/dashboards/14282-cadvisor-exporter/