---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: backend
spec:
  selector:
    app: postgres-notification
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-notification
  namespace: backend
spec:
  serviceName: postgres-notification
  selector:
    matchLabels:
      app: postgres-notification
  template:
    metadata:
      labels:
        app: postgres-notification
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-notification
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-notification
                  key: POSTGRES_PASSWORD
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-notification
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-notification-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-notification-storage
          persistentVolumeClaim:
            claimName: postgres-notification-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-notification-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-notification-pv
  namespace: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-notification

