apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-lodging
  namespace: backend
type: Opaque
data:
# needed for both postgres statefulSet and initContainer
  POSTGRES_USER: cG9zdGdyZXM=
  # needed for shell script inside initContainer of Service Deployment
  PGPASSWORD: cm9vdA==
  # needed for postgres statefulSet
  POSTGRES_PASSWORD: cm9vdA==
